"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});
// This on "One Dark Pro" VSCode theme converted to Monaco format
exports.default = {
    type: "dark",
    inherit: false,
    base: "vs-dark",
    colors: {
        "activityBar.background": "#282c34",
        "activityBar.foreground": "#d7dae0",
        "activityBarBadge.background": "#4d78cc",
        "activityBarBadge.foreground": "#f8fafd",
        "badge.background": "#282c34",
        "button.background": "#404754",
        "debugToolBar.background": "#21252b",
        "diffEditor.insertedTextBackground": "#00809b33",
        "dropdown.background": "#21252b",
        "dropdown.border": "#21252b",
        "editor.background": "#282c34",
        "editor.foreground": "#abb2bf",
        "editorError.foreground": "#c24038",
        "editorIndentGuide.activeBackground": "#c8c8c859",
        "editorMarkerNavigation.background": "#21252b",
        "editorRuler.foreground": "#abb2bf26",
        "editor.lineHighlightBackground": "#2c313c",
        "editor.selectionBackground": "#67769660",
        "editor.selectionHighlightBackground": "#ffffff10",
        "editor.selectionHighlightBorder": "#ddd",
        "editorCursor.background": "#ffffffc9",
        "editorCursor.foreground": "#528bff",
        "editorBracketMatch.border": "#515a6b",
        "editorBracketMatch.background": "#515a6b",
        "editor.findMatchBackground": "#42557b",
        "editor.findMatchBorder": "#457dff",
        "editor.findMatchHighlightBackground": "#314365",
        "editor.wordHighlightBackground": "#484e5b",
        "editor.wordHighlightBorder": "#7f848e",
        "editor.wordHighlightStrongBackground": "#abb2bf26",
        "editor.wordHighlightStrongBorder": "#7f848e",
        "editorGroup.background": "#181a1f",
        "editorGroup.border": "#181a1f",
        "editorGroupHeader.tabsBackground": "#21252b",
        "editorIndentGuide.background": "#3b4048",
        "editorLineNumber.foreground": "#495162",
        "editorActiveLineNumber.foreground": "#737984",
        "editorWhitespace.foreground": "#3b4048",
        "editorHoverWidget.background": "#21252b",
        "editorHoverWidget.border": "#181a1f",
        "editorSuggestWidget.background": "#21252b",
        "editorSuggestWidget.border": "#181a1f",
        "editorSuggestWidget.selectedBackground": "#2c313a",
        "editorWidget.background": "#21252b",
        "focusBorder": "#464646",
        "input.background": "#1d1f23",
        "list.activeSelectionBackground": "#2c313a",
        "list.activeSelectionForeground": "#d7dae0",
        "list.focusBackground": "#383e4a",
        "list.hoverBackground": "#292d35",
        "list.highlightForeground": "#c5c5c5",
        "list.inactiveSelectionBackground": "#2c313a",
        "list.inactiveSelectionForeground": "#d7dae0",
        "peekViewEditor.background": "#1b1d23",
        "peekViewEditor.matchHighlightBackground": "#29244b",
        "peekViewResult.background": "#22262b",
        "scrollbarSlider.background": "#4e566660",
        "scrollbarSlider.activeBackground": "#747d9180",
        "scrollbarSlider.hoverBackground": "#5a637580",
        "sideBar.background": "#21252b",
        "sideBarSectionHeader.background": "#282c34",
        "statusBar.background": "#21252b",
        "statusBar.foreground": "#9da5b4",
        "statusBarItem.hoverBackground": "#2c313a",
        "statusBar.noFolderBackground": "#21252b",
        "statusBar.debuggingBackground": "#7e0097",
        "statusBar.debuggingBorder": "#66017a",
        "statusBar.debuggingForeground": "#ffffff",
        "statusBarItem.remoteForeground": "#f8fafd",
        "statusBarItem.remoteBackground": "#4d78cc",
        "tab.activeBackground": "#282c34",
        "tab.border": "#181a1f",
        "tab.inactiveBackground": "#21252b",
        "tab.hoverBackground": "#323842",
        "tab.unfocusedHoverBackground": "#323842",
        "terminal.foreground": "#c8c8c8",
        "terminal.ansiBlack": "#2d3139",
        "terminal.ansiBlue": "#61afef",
        "terminal.ansiGreen": "#98c379",
        "terminal.ansiYellow": "#e5c07b",
        "terminal.ansiCyan": "#56b6c2",
        "terminal.ansiMagenta": "#c678dd",
        "terminal.ansiRed": "#e06c75",
        "terminal.ansiWhite": "#d7dae0",
        "terminal.ansiBrightBlack": "#7f848e",
        "terminal.ansiBrightBlue": "#528bff",
        "terminal.ansiBrightGreen": "#98c379",
        "terminal.ansiBrightYellow": "#e5c07b",
        "terminal.ansiBrightCyan": "#56b6c2",
        "terminal.ansiBrightMagenta": "#7e0097",
        "terminal.ansiBrightRed": "#f44747",
        "terminal.ansiBrightWhite": "#d7dae0",
        "titleBar.activeBackground": "#282c34",
        "titleBar.activeForeground": "#9da5b4",
        "titleBar.inactiveBackground": "#21252b",
        "titleBar.inactiveForeground": "#6b717d",
        "textLink.foreground": "#61afef"
    },
    rules: [{
        "token": "support.variable.magic.python",
        "foreground": "#ef596f"
    }, {
        "token": "punctuation.separator.period.python",
        "foreground": "#abb2bf"
    }, {
        "token": "punctuation.separator.element.python",
        "foreground": "#abb2bf"
    }, {
        "token": "punctuation.parenthesis.begin.python",
        "foreground": "#abb2bf"
    }, {
        "token": "punctuation.parenthesis.end.python",
        "foreground": "#abb2bf"
    }, {
        "token": "",
        "foreground": "#abb2bf"
    }, {
        "token": "variable.parameter.function.language.special.self.python",
        "foreground": "#e5c07b"
    }, {
        "token": "support.constant.edge",
        "foreground": "#d55fde"
    }, {
        "token": "constant.other.character-class.regexp",
        "foreground": "#ef596f"
    }, {
        "token": "keyword.operator.quantifier.regexp",
        "foreground": "#d19a66"
    }, {
        "token": "punctuation.definition.string.begin",
        "foreground": "#89ca78"
    }, {
        "token": "punctuation.definition.string.end",
        "foreground": "#89ca78"
    }, {
        "token": "variable.parameter.function",
        "foreground": "#abb2bf"
    }, {
        "token": "comment",
        "foreground": "#7f848e",
        "fontStyle": "italic"
    }, {
        "token": "punctuation.definition.comment",
        "foreground": "#7f848e",
        "fontStyle": "italic"
    }, {
        "token": "comment markup.link",
        "foreground": "#5c6370"
    }, {
        "token": "markup.changed.diff",
        "foreground": "#e5c07b"
    }, {
        "token": "meta.diff.header.from-file",
        "foreground": "#61afef"
    }, {
        "token": "punctuation.definition.from-file.diff",
        "foreground": "#61afef"
    }, {
        "token": "markup.inserted.diff",
        "foreground": "#89ca78"
    }, {
        "token": "markup.deleted.diff",
        "foreground": "#ef596f"
    }, {
        "token": "punctuation.separator.key-value",
        "foreground": "#abb2bf"
    }, {
        "token": "entity.other.attribute-name.js",
        "fontStyle": "italic"
    }, {
        "token": "entity.other.attribute-name.ts",
        "fontStyle": "italic"
    }, {
        "token": "entity.other.attribute-name.jsx",
        "fontStyle": "italic"
    }, {
        "token": "entity.other.attribute-name.tsx",
        "fontStyle": "italic"
    }, {
        "token": "variable.parameter",
        "fontStyle": "italic"
    }, {
        "token": "variable.language.super",
        "fontStyle": "italic"
    }, {
        "token": "keyword.operator.expression.import",
        "foreground": "#61afef"
    }, {
        "token": "support.constant.math",
        "foreground": "#e5c07b"
    }, {
        "token": "support.constant.property.math",
        "foreground": "#d19a66"
    }, {
        "token": "variable.other.constant",
        "foreground": "#e5c07b"
    }, {
        "token": "keyword.operator.logical.js",
        "foreground": "#2bbac5"
    }, {
        "token": "keyword.operator.bitwise",
        "foreground": "#2bbac5"
    }, {
        "token": "keyword.operator.channel",
        "foreground": "#2bbac5"
    }, {
        "token": "support.constant.property-value.scss",
        "foreground": "#d19a66"
    }, {
        "token": "support.constant.property-value.css",
        "foreground": "#d19a66"
    }, {
        "token": "keyword.operator.css",
        "foreground": "#2bbac5"
    }, {
        "token": "keyword.operator.scss",
        "foreground": "#2bbac5"
    }, {
        "token": "keyword.operator.less",
        "foreground": "#2bbac5"
    }, {
        "token": "support.constant.color.w3c-standard-color-name.css",
        "foreground": "#d19a66"
    }, {
        "token": "support.constant.color.w3c-standard-color-name.scss",
        "foreground": "#d19a66"
    }, {
        "token": "punctuation.separator.list.comma.css",
        "foreground": "#abb2bf"
    }, {
        "token": "support.constant.color.w3c-standard-color-name.css",
        "foreground": "#d19a66"
    }, {
        "token": "support.type.vendored.property-name.css",
        "foreground": "#2bbac5"
    }, {
        "token": "punctuation.definition.template-expression.begin",
        "foreground": "#ef596f"
    }, {
        "token": "punctuation.definition.template-expression.end",
        "foreground": "#ef596f"
    }, {
        "token": "support.module.node",
        "foreground": "#e5c07b"
    }, {
        "token": "support.type.object.module",
        "foreground": "#e5c07b"
    }, {
        "token": "support.module.node",
        "foreground": "#e5c07b"
    }, {
        "token": "entity.name.type.module",
        "foreground": "#e5c07b"
    }, {
        "token": "variable.other.readwrite",
        "foreground": "#ef596f"
    }, {
        "token": "meta.object-literal.key",
        "foreground": "#ef596f"
    }, {
        "token": "support.variable.property",
        "foreground": "#ef596f"
    }, {
        "token": "support.variable.object.process",
        "foreground": "#ef596f"
    }, {
        "token": "support.variable.object.node",
        "foreground": "#ef596f"
    }, {
        "token": "comment.line.double-slash",
        "fontStyle": "italic"
    }, {
        "token": "comment.block.documentation",
        "fontStyle": "italic"
    }, {
        "token": "support.constant.json",
        "foreground": "#d19a66"
    }, {
        "token": "keyword.operator.expression.instanceof",
        "foreground": "#d55fde"
    }, {
        "token": "keyword.operator.new",
        "foreground": "#d55fde"
    }, {
        "token": "keyword.operator.ternary",
        "foreground": "#d55fde"
    }, {
        "token": "keyword.operator.optional",
        "foreground": "#d55fde"
    }, {
        "token": "support.type.object.console",
        "foreground": "#ef596f"
    }, {
        "token": "support.variable.property.process",
        "foreground": "#d19a66"
    }, {
        "token": "entity.name.function",
        "foreground": "#61afef"
    }, {
        "token": "support.function.console",
        "foreground": "#61afef"
    }, {
        "token": "keyword.operator",
        "foreground": "#2bbac5"
    }, {
        "token": "keyword.operator.delete",
        "foreground": "#d55fde"
    }, {
        "token": "support.type.object.dom",
        "foreground": "#2bbac5"
    }, {
        "token": "support.variable.dom",
        "foreground": "#ef596f"
    }, {
        "token": "support.variable.property.dom",
        "foreground": "#ef596f"
    }, {
        "token": "keyword.operator.arithmetic",
        "foreground": "#2bbac5"
    }, {
        "token": "keyword.operator.comparison",
        "foreground": "#2bbac5"
    }, {
        "token": "keyword.operator.decrement",
        "foreground": "#2bbac5"
    }, {
        "token": "keyword.operator.increment",
        "foreground": "#2bbac5"
    }, {
        "token": "punctuation.separator.delimiter",
        "foreground": "#abb2bf"
    }, {
        "token": "variable.parameter.function.language.python",
        "foreground": "#d19a66"
    }, {
        "token": "support.type.python",
        "foreground": "#2bbac5"
    }, {
        "token": "keyword.operator.logical.python",
        "foreground": "#d55fde"
    }, {
        "token": "variable.parameter.function.python",
        "foreground": "#d19a66"
    }, {
        "token": "punctuation.definition.arguments.begin.python",
        "foreground": "#abb2bf"
    }, {
        "token": "punctuation.definition.arguments.end.python",
        "foreground": "#abb2bf"
    }, {
        "token": "punctuation.separator.arguments.python",
        "foreground": "#abb2bf"
    }, {
        "token": "punctuation.definition.list.begin.python",
        "foreground": "#abb2bf"
    }, {
        "token": "punctuation.definition.list.end.python",
        "foreground": "#abb2bf"
    }, {
        "token": "meta.function-call.generic.python",
        "foreground": "#61afef"
    }, {
        "token": "constant.character.format.placeholder.other.python",
        "foreground": "#89ca78"
    }, {
        "token": "none",
        "foreground": "#abb2bf"
    }, {
        "token": "keyword.operator",
        "foreground": "#abb2bf"
    }, {
        "token": "keyword.operator.assignment.compound",
        "foreground": "#d55fde"
    }, {
        "token": "keyword",
        "foreground": "#d55fde"
    }, {
        "token": "variable",
        "foreground": "#ef596f"
    }, {
        "token": "variable.language",
        "foreground": "#e5c07b"
    }, {
        "token": "token.package.keyword",
        "foreground": "#d55fde"
    }, {
        "token": "token.package",
        "foreground": "#abb2bf"
    }, {
        "token": "entity.name.function",
        "foreground": "#61afef"
    }, {
        "token": "meta.require",
        "foreground": "#61afef"
    }, {
        "token": "support.function.any-method",
        "foreground": "#61afef"
    }, {
        "token": "variable.function",
        "foreground": "#61afef"
    }, {
        "token": "entity.name.type.namespace",
        "foreground": "#e5c07b"
    }, {
        "token": "support.class",
        "foreground": "#e5c07b"
    }, {
        "token": "entity.name.type.class",
        "foreground": "#e5c07b"
    }, {
        "token": "entity.name.class.identifier.namespace.type",
        "foreground": "#e5c07b"
    }, {
        "token": "entity.name.class",
        "foreground": "#e5c07b"
    }, {
        "token": "variable.other.class.js",
        "foreground": "#e5c07b"
    }, {
        "token": "variable.other.class.ts",
        "foreground": "#e5c07b"
    }, {
        "token": "entity.name.type",
        "foreground": "#e5c07b"
    }, {
        "token": "keyword.control",
        "foreground": "#d55fde"
    }, {
        "token": "keyword.control.import.python",
        "fontStyle": "italic"
    }, {
        "token": "keyword.control.flow.python",
        "fontStyle": "italic"
    }, {
        "token": "control.elements",
        "foreground": "#d19a66"
    }, {
        "token": "keyword.operator.less",
        "foreground": "#d19a66"
    }, {
        "token": "keyword.other.special-method",
        "foreground": "#61afef"
    }, {
        "token": "storage",
        "foreground": "#d55fde"
    }, {
        "token": "token.storage",
        "foreground": "#d55fde"
    }, {
        "token": "keyword.operator.expression.delete",
        "foreground": "#d55fde"
    }, {
        "token": "keyword.operator.expression.in",
        "foreground": "#d55fde"
    }, {
        "token": "keyword.operator.expression.of",
        "foreground": "#d55fde"
    }, {
        "token": "keyword.operator.expression.instanceof",
        "foreground": "#d55fde"
    }, {
        "token": "keyword.operator.new",
        "foreground": "#d55fde"
    }, {
        "token": "keyword.operator.expression.typeof",
        "foreground": "#d55fde"
    }, {
        "token": "keyword.operator.expression.void",
        "foreground": "#d55fde"
    }, {
        "token": "support.function",
        "foreground": "#2bbac5"
    }, {
        "token": "support.type.property-name",
        "foreground": "#abb2bf"
    }, {
        "token": "support.constant.property-value",
        "foreground": "#abb2bf"
    }, {
        "token": "support.constant.font-name",
        "foreground": "#d19a66"
    }, {
        "token": "meta.tag",
        "foreground": "#abb2bf"
    }, {
        "token": "string",
        "foreground": "#89ca78"
    }, {
        "token": "entity.other.inherited-class",
        "foreground": "#89ca78"
    }, {
        "token": "constant.other.symbol",
        "foreground": "#2bbac5"
    }, {
        "token": "constant.numeric",
        "foreground": "#d19a66"
    }, {
        "token": "none",
        "foreground": "#d19a66"
    }, {
        "token": "none",
        "foreground": "#d19a66"
    }, {
        "token": "constant",
        "foreground": "#d19a66"
    }, {
        "token": "punctuation.definition.constant",
        "foreground": "#d19a66"
    }, {
        "token": "entity.name.tag",
        "foreground": "#ef596f"
    }, {
        "token": "entity.other.attribute-name",
        "foreground": "#d19a66"
    }, {
        "token": "entity.other.attribute-name.id",
        "foreground": "#61afef",
        "fontStyle": "normal"
    }, {
        "token": "entity.other.attribute-name.class.css",
        "foreground": "#d19a66",
        "fontStyle": "normal"
    }, {
        "token": "meta.selector",
        "foreground": "#d55fde"
    }, {
        "token": "none",
        "foreground": "#d19a66"
    }, {
        "token": "markup.heading",
        "foreground": "#ef596f",
        "fontStyle": "bold"
    }, {
        "token": "markup.heading punctuation.definition.heading",
        "foreground": "#61afef"
    }, {
        "token": "entity.name.section",
        "foreground": "#61afef"
    }, {
        "token": "keyword.other.unit",
        "foreground": "#ef596f"
    }, {
        "token": "markup.bold",
        "foreground": "#d19a66",
        "fontStyle": "bold"
    }, {
        "token": "todo.bold",
        "foreground": "#d19a66",
        "fontStyle": "bold"
    }, {
        "token": "punctuation.definition.bold",
        "foreground": "#e5c07b"
    }, {
        "token": "markup.italic",
        "foreground": "#d55fde"
    }, {
        "token": "punctuation.definition.italic",
        "foreground": "#d55fde"
    }, {
        "token": "todo.emphasis",
        "foreground": "#d55fde"
    }, {
        "token": "emphasis md",
        "foreground": "#d55fde"
    }, {
        "token": "string.regexp",
        "foreground": "#2bbac5"
    }, {
        "token": "constant.character.escape",
        "foreground": "#2bbac5"
    }, {
        "token": "punctuation.section.embedded",
        "foreground": "#ef596f"
    }, {
        "token": "variable.interpolation",
        "foreground": "#ef596f"
    }, {
        "token": "invalid.illegal",
        "foreground": "#ffffff"
    }, {
        "token": "invalid.broken",
        "foreground": "#ffffff"
    }, {
        "token": "invalid.deprecated",
        "foreground": "#ffffff"
    }, {
        "token": "invalid.unimplemented",
        "foreground": "#ffffff"
    }, {
        "token": "source.json meta.structure.dictionary.json > string.quoted.json",
        "foreground": "#ef596f"
    }, {
        "token": "source.json meta.structure.dictionary.json > string.quoted.json > punctuation.string",
        "foreground": "#ef596f"
    }, {
        "token": "source.json meta.structure.dictionary.json > value.json > string.quoted.json",
        "foreground": "#89ca78"
    }, {
        "token": "source.json meta.structure.array.json > value.json > string.quoted.json",
        "foreground": "#89ca78"
    }, {
        "token": "source.json meta.structure.dictionary.json > value.json > string.quoted.json > punctuation",
        "foreground": "#89ca78"
    }, {
        "token": "source.json meta.structure.array.json > value.json > string.quoted.json > punctuation",
        "foreground": "#89ca78"
    }, {
        "token": "source.json meta.structure.dictionary.json > constant.language.json",
        "foreground": "#2bbac5"
    }, {
        "token": "source.json meta.structure.array.json > constant.language.json",
        "foreground": "#2bbac5"
    }, {
        "token": "support.type.property-name.json",
        "foreground": "#ef596f"
    }, {
        "token": "support.type.property-name.json punctuation",
        "foreground": "#ef596f"
    }, {
        "token": "meta.function.decorator.python",
        "foreground": "#61afef"
    }, {
        "token": "support.token.decorator.python",
        "foreground": "#2bbac5"
    }, {
        "token": "meta.function.decorator.identifier.python",
        "foreground": "#2bbac5"
    }, {
        "token": "function.parameter",
        "foreground": "#d19a66"
    }, {
        "token": "function.parameter",
        "foreground": "#abb2bf"
    }, {
        "token": "function.brace",
        "foreground": "#abb2bf"
    }, {
        "token": "rgb-value",
        "foreground": "#2bbac5"
    }, {
        "token": "inline-color-decoration rgb-value",
        "foreground": "#d19a66"
    }, {
        "token": "less rgb-value",
        "foreground": "#d19a66"
    }, {
        "token": "selector.sass",
        "foreground": "#ef596f"
    }, {
        "token": "support.type.primitive.ts",
        "foreground": "#e5c07b"
    }, {
        "token": "support.type.builtin.ts",
        "foreground": "#e5c07b"
    }, {
        "token": "support.type.primitive.tsx",
        "foreground": "#e5c07b"
    }, {
        "token": "support.type.builtin.tsx",
        "foreground": "#e5c07b"
    }, {
        "token": "block.scope.end",
        "foreground": "#abb2bf"
    }, {
        "token": "block.scope.begin",
        "foreground": "#abb2bf"
    }, {
        "token": "storage.type.cs",
        "foreground": "#e5c07b"
    }, {
        "token": "entity.name.variable.local.cs",
        "foreground": "#ef596f"
    }, {
        "token": "token.info-token",
        "foreground": "#61afef"
    }, {
        "token": "token.warn-token",
        "foreground": "#d19a66"
    }, {
        "token": "token.error-token",
        "foreground": "#f44747"
    }, {
        "token": "token.debug-token",
        "foreground": "#d55fde"
    }, {
        "token": "punctuation.definition.template-expression.begin",
        "foreground": "#d55fde"
    }, {
        "token": "punctuation.definition.template-expression.end",
        "foreground": "#d55fde"
    }, {
        "token": "punctuation.section.embedded",
        "foreground": "#d55fde"
    }, {
        "token": "meta.template.expression",
        "foreground": "#abb2bf"
    }, {
        "token": "keyword.operator.module",
        "foreground": "#d55fde"
    }, {
        "token": "support.type.type.flowtype",
        "foreground": "#61afef"
    }, {
        "token": "support.type.primitive",
        "foreground": "#e5c07b"
    }, {
        "token": "meta.property.object",
        "foreground": "#ef596f"
    }, {
        "token": "variable.parameter.function.js",
        "foreground": "#ef596f"
    }, {
        "token": "variable.parameter.js",
        "foreground": "#ef596f"
    }, {
        "token": "keyword.other.template.begin",
        "foreground": "#89ca78"
    }, {
        "token": "keyword.other.template.end",
        "foreground": "#89ca78"
    }, {
        "token": "keyword.other.substitution.begin",
        "foreground": "#89ca78"
    }, {
        "token": "keyword.other.substitution.end",
        "foreground": "#89ca78"
    }, {
        "token": "keyword.operator.assignment",
        "foreground": "#2bbac5"
    }, {
        "token": "punctuation.quasi.element",
        "foreground": "#d55fde"
    }, {
        "token": "constant.character.entity",
        "foreground": "#ef596f"
    }, {
        "token": "entity.other.attribute-name.pseudo-element",
        "foreground": "#2bbac5"
    }, {
        "token": "entity.other.attribute-name.pseudo-class",
        "foreground": "#2bbac5"
    }, {
        "token": "entity.global.clojure",
        "foreground": "#e5c07b"
    }, {
        "token": "meta.symbol.clojure",
        "foreground": "#ef596f"
    }, {
        "token": "constant.keyword.clojure",
        "foreground": "#2bbac5"
    }, {
        "token": "source.ini",
        "foreground": "#89ca78"
    }, {
        "token": "meta.scope.prerequisites.makefile",
        "foreground": "#ef596f"
    }, {
        "token": "source.makefile",
        "foreground": "#e5c07b"
    }, {
        "token": "support.variable.semantic.hlsl",
        "foreground": "#e5c07b"
    }, {
        "token": "support.type.texture.hlsl",
        "foreground": "#d55fde"
    }, {
        "token": "support.type.sampler.hlsl",
        "foreground": "#d55fde"
    }, {
        "token": "support.type.object.hlsl",
        "foreground": "#d55fde"
    }, {
        "token": "support.type.object.rw.hlsl",
        "foreground": "#d55fde"
    }, {
        "token": "support.type.fx.hlsl",
        "foreground": "#d55fde"
    }, {
        "token": "support.type.object.hlsl",
        "foreground": "#d55fde"
    }, {
        "token": "text.variable",
        "foreground": "#ef596f"
    }, {
        "token": "text.bracketed",
        "foreground": "#ef596f"
    }, {
        "token": "support.type.vb.asp",
        "foreground": "#e5c07b"
    }]
};